- src/plugins/Core/plugins/guess.py
- src/plugins/Core/plugins/report.py
---
---
已完成的部分：（下文引用自 [TODO.txt](https://github.com/This-is-XiaoDeng/XDbot2/blob/master/TODO.txt)）
> /report（权限：ALL，{反馈}，重定向至github）
/guess（权限：ALL，{猜数字|gn}）
/guess {start|开始}
/guess < NUM >
> [add]猜数字 & 反馈

- src/plugins/Core/plugins/sign.py
> [add] 签到排行榜

- src/plugins/Core/plugins/_userCtrl.py
- src/plugins/Core/plugins/autosell.py
- src/plugins/Core/plugins/su.py
- 二十面骰投出1时不会清空 VimCoin , 而会扣除 50vi (可以为负)
- autosell 支持自定义出售者
- autosell 支持设置限购
autosell 命令格式修改为：
`su shop add <id> <count> <price> <data> [maxBuy] [nickname] [user_id]`
> [update] 修改二十面骰、优化autosell及其命令

- src/plugins/Core/plugins/sign.py
显示下次可签到时间，计算表达式（秒）：`int((int(time.time()/86400)+1)*86400-time.time())`
> [add] sign (rank) 时显示下次可签到时间

- src/plugins/Core/plugins/su.py
`/su *log` `-Y`YYYY `-M`MM `-D`DD `-h`hh `-m`mm `-s`ss `-u`userid `-g`groupid `-c`command
都是可选
`-c`的command中用`^`代替` `
> [add] su审核日志:详细匹配

- src/plugins/Core/lang/en_laman28.json
- Fix a bug which made by myself (((
> Fix a bug which made by myself (

- src/plugins/Core/plugins/gssearch.py
> [add] 原神攻略查询功能

- src/plugins/Core/plugins/_gssearch.py
- src/plugins/Core/plugins/gssearch.py
Just I think,because my bot still can't login.
> [fix]repair the bug which made by myself

- src/plugins/Core/lang/zh_bronya.json
> 我 t m 就 是 个 傻 逼

- src/plugins/Core/plugins/cave.py
- src/plugins/Core/plugins/etm/economy.py
- src/plugins/Core/plugins/quick_math.py
- 当每一条quick math无回答自动撤回之后：群聊的未回答计数+1
- 如果未回答计数 >= 3 则不会再发
- 当群内收到消息之后：
- 10%概率 未回答计数=0
- 10%概率 未回答计数=1
- 30%概率 未回答计数=2
- 50%概率 未回答计数=3（不变，还是不会发）
> [update] quick math 群聊热度检测

- src/plugins/Core/config.py
- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/etm/achievement.py
- src/plugins/Core/plugins/etm/book_and_quill.py
- src/plugins/Core/plugins/github.py
- src/plugins/Core/plugins/reply.py
- src/plugins/Core/plugins/su_notice.py
- src/plugins/Core/plugins/su_old.py
> 添加GitHub解析插件

- README.md
- src/plugins/Core/plugins/quick_calculus.py
> 为快速微积分添加求极限

- src/plugins/Core/config.py
- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/achievement.py
- src/plugins/Core/plugins/etm/buff.py
- src/plugins/Core/plugins/etm/data.py
- src/plugins/Core/plugins/etm/dice.py
- src/plugins/Core/plugins/etm/item_basic_data.py
- src/plugins/Core/plugins/etm/items.py
- src/plugins/Core/plugins/etm/talisman.py
- src/plugins/Core/plugins/market.py
- src/plugins/Core/plugins/quick_math.py
- src/plugins/Core/plugins/shop.py
> 添加插件：全球市场 & 添加物品：护符

- src/plugins/Core/plugins/quick_calculus.py
原文本：
I. `[QUICK CAICULUS] 求函数 f(x) = x**3 + 8*x**2 + 2*x + 9 的二阶导数`
II. `[QUICK CAICULUS] 求函数 f(x) = 6*x**3 + 9*x**2 + 9*x + 6 的导数`
格式化后：
I. `[QUICK CAICULUS] 求函数 f(x) = x³ + 8x² + 2x + 9 的二阶导数`
II. `[QUICK CAICULUS] 求函数 f(x) = 6x³ + 9x² + 9x + 6 的导数`
原文本：
I. `6*x**2+7*x+8`
II. `6x^2+7x+8`
III. `6x²+7x+8`
IV. `6*x^2+7x+8`
V. `6x²+7*x+8`
若答案判错，则格式化后再次尝试判断：
I. `6*x**2+7*x+8`
II. `6*x**2+7*x+8`
III. `6*x**2+7*x+8`
IV. `6*x**2+7*x+8`
V. `6*x**2+7*x+8`
> [update] 格式化快速微积分输出/回答

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/_error.py
- src/plugins/Core/plugins/fakenode.py
- src/plugins/Core/plugins/help.py
- src/plugins/Core/plugins/reply.py
- [fix] 修复删图概率过高导致图片急速流失问题
- [add] 合并转发帮助
- [fix] 尝试修复部分问题并整理代码
- [update] 重命名部分变量
- [fix] 修复无法正常发送合并转发消息的问题
- [update] 更新帮助展示格式
- [fix] 修复帮助显示不正常的问题
- [update] 更新小贴士
- [update] 修改排版
在群聊使用`/help`时将使用合并转发发送指令列表和每个指令的用法
> 对/help添加合并转发

- .github/workflows/welcome-issue.yml
- src/plugins/Core/plugins/email.py
> 添加 Issue 自动欢迎

- src/plugins/Core/plugins/ghot.py
- src/plugins/Core/plugins/man.py
> 修复 ghot 在获取群名失败时直接报错的问题

- README.md
> [update] 新增一个卡片

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/_error.py
- src/plugins/Core/plugins/essencemsg.py
- src/plugins/Core/plugins/groupwelcome.py
issues :
- https://github.com/ITCraftDevelopmentTeam/XDbot2/issues/251
- https://github.com/ITCraftDevelopmentTeam/XDbot2/issues/219
> [add] 关键词设置精华消息 & 入群欢迎

- src/plugins/Core/plugins/su_reply.py
> [update] 重构 `su reply`

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/etm/auto_sign_coupon.py
- src/plugins/Core/plugins/etm/items.py
- src/plugins/Core/plugins/quick_math.py
- src/plugins/Core/plugins/sign.py
> [add] 自动签到券

- src/plugins/Core/plugins/sixcount.py
> [update] 在 sixcount 中合并数量 <= 10 的用户

- Dockerfile
- requirements.txt
> [update] 改写 Dockerfile

- src/plugins/Core/plugins/bank.py
> [fix] 修复已知问题

- src/plugins/Core/plugins/etm/pouch.py
> [fix]修复一个收纳袋bug

- .gitmodules
- .vscode/settings.json
- requirements.txt
- src/plugins/Core/plugins/man.py
- [update] 将 markdown2png 更换为 MarkDown2Image
- [update] 完成全部替换
This-is-XiaoDeng/markdown2png 因为过于屎山已停止维护
> 将 markdown2png 替换为 MarkDown2Image

- src/plugins/Core/plugins/quick_math.py
> [fix] 修复`nqm`群聊不固定的bug

- .vscode/settings.json
- src/plugins/Core/config.py
- src/plugins/Core/plugins/cave.py
- src/plugins/Core/plugins/quick_math.py
- [update] 修改 CAVE 冷却时间 (#315)
- [update] 更改 cave 评论匹配模式
- [update] 修改 cave 相关权限及 help
- [fix] 修复小数无法通过 quick_math 验证的问题
> cave 冷却时间及一些更改 (#315)

- src/plugins/Core/plugins/etm/pawcoin.py
- src/plugins/Core/plugins/quick_math.py
感觉没必要发那么多，改成2个未回答我觉得就可以了
未回答达到2次后，每次收到消息时触发：
- `50%` 概率还是不发
- `40%` 概率会再发1次
- `10%` 概率会再发2次
还是一样的逻辑，有人回答之后就固定会再发2次
> [update] 修改quick math未回答计数上限

- src/plugins/Core/config.py
- src/plugins/Core/plugins/su_cave.py
> [add] cave restore

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/pacman.py
> [update] pacman: multi language support

- src/plugins/Core/plugins/essencemsg.py
> [update] essencemsg: reply to set essence msg

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/chatgptv2.py
- src/plugins/Core/plugins/gpt.py
- src/plugins/Core/plugins/jrrp.py
- src/plugins/Core/plugins/pay.py
- [fix] 修复 jrrp 在八点刷新的问题
- [remove] 删除无效键
- [update] 将 gpt 接入 xdbot2gptv2
- [update] 更改扣除倍率
- [update] No Token Error
> 将 gpt.py 接入 XDbot2GPTv2 && 修复 pay 插件

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/gpt.py
- src/plugins/Core/plugins/redpacket.py
> 修复重启后红包丢失的问题

- src/plugins/Core/duel/base_properties/primary.json
- src/plugins/Core/duel/effect_functions.txt
- src/plugins/Core/duel/kits/ice_king.json
- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/duel/monomer.py
- src/plugins/Core/plugins/duel/path.py
- src/plugins/Core/plugins/market.py
- [add] 添加套装数据：寒冰王者
- [add] 新建部分文件
- [add] gain加载
- [add] 完成部分 effect func
- [update] 在 token 不足时添加购买提示
- [fix] 修复 market 无法批量购买的问题
> 完成 duel 部分方法 && 修改 Token 不足时的提示 && 修复 market 无法批量购买的问题

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/duel/monomer.py
- src/plugins/Core/plugins/duel/scheduler.py
- src/plugins/Core/plugins/market.py
- update.py
- [add] 添加基础调度器 我不确定for这么写会不会炸 XDbot好像已经这么炸过一次了
- [update] 添加部分变量
- [update] 手动格式化代码
- [add] 添加 market search 子命令 (#404)
- [update] 更新语言
- [add] 允许搜索 display_name、display_message
- [update] 更新lang
fix #404
> 添加 market search 

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/_utils.py
- src/plugins/Core/plugins/duel/controller.py
- src/plugins/Core/plugins/duel/scheduler.py
- src/plugins/Core/plugins/etm/dice.py
- src/plugins/Core/plugins/etm/item.py
- src/plugins/Core/plugins/etm/items.py
- src/plugins/Core/plugins/etm/mystery_box.py
- src/plugins/Core/plugins/etm/pawcoin.py
- src/plugins/Core/plugins/synthesis.py
- src/plugins/Core/synthesis/mysterybox_lv1.json
- update.py
- [update] 更新调度器全部 for 以防 bug
- [add] 添加合成模块
- [update] 完成合成模块
- [add] 添加入口
- [update] 合成后添加经验
- [fix] fxi a bug
- [update] 更新帮助及物品介绍
- [update] 修改物品介绍
- [update] 更改物品介绍
- [update] 修改物品介绍
> 添加合成模块 && 修改部分物品简介

- src/plugins/Core/plugins/essencemsg.py
- src/plugins/Core/plugins/quickmath_points.py
使用 keyword 匹配替换 regex。
fix #384
> [update] essencemsg: use endswith

- src/plugins/Core/plugins/su_ban.py
> 修复 suban 不指定原因时报错的问题

- src/plugins/Core/lang/zh_hans.json
修复`quickmath.qus_count`缺少换行的问题
请手动同步到`develop`分支
> [fix] fix a bug

- src/plugins/Core/plugins/node_manager.py
> [add] Change Branch

- src/plugins/Core/plugins/quickmath.py
> [add] 为 QuickMath 添加群判断

- src/plugins/Core/plugins/whoAtme.py
> [add] 恢复老版本的 whoAtme 插件

- src/plugins/Core/plugins/chatgptv2.py
- src/plugins/Core/plugins/etm/buff.py
- src/plugins/Core/plugins/etm/buffs.json
- src/plugins/Core/plugins/etm/data.py
- src/plugins/Core/plugins/etm/exp.py
- src/plugins/Core/plugins/sign.py
- [update] 用户等级大于等于30时每日获得5次GPT限免 再这么玩，XDbotGPT都快白送了（
为等级 >= 30 的用户提供每日 5 次的 GPT 限免
签到即可领取，仅当日使用
提示还没想好怎么写（建议写了再合并）
我不确定还有没有其他问题，反正我测试了能跑
> 为大于三十级的用户提供每日五次GPT限免

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/_utils.py
- src/plugins/Core/plugins/smart_reply.py
- [add] support: reply fork
- [update] change reply command doc
- [update] 修改数据编号检查方式
> add: reply fork

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/_utils.py
- src/plugins/Core/plugins/duel_command.py
- [add] 添加决斗总结提示
- [fix] Fix a bug
- [fix] try to fix a bug
> 添加决斗结束后带有结果的提示

- src/plugins/Core/lang/zh_hans.json
> 更新今日人品用户协议

- src/plugins/Core/duel/buff/action_again.json
- src/plugins/Core/duel/buff/reduce_speed_010.json
- src/plugins/Core/duel/kits/ice_king.json
- src/plugins/Core/duel/kits/whirlwind_dancer.json
- src/plugins/Core/plugins/duel/monomer.py
> [add] 添加装备：风之舞者

- requirements.txt
- src/plugins/Core/plugins/bots.py
- [add] 添加一个钩子函数
1. 删除了依赖列表中的版本指定
2. 在 Bot 调用 API 失败后尝试在其他 Bot 上执行
> 多平台 bots 适配

- src/plugins/Core/plugins/chatgptv2.py
- src/plugins/Core/plugins/gptcommandhelp.py
修复了 openai 库更新到 1.0.0+ 后用法被更改导致 gpt 相关功能无法正常运行的问题
------
- [update] 新增对于 OpenAI >= 1.0.0 的支持
- [fix] 使 gptcommandhelp 支持 OpenAI Lib V1
- [fix] 修复 token <= 0 时无法使用 gch 的问题
> 对于 openai-python >= 1.0.0 的支持

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/preview.py
> [add] 自动 Preview (#435)

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/_bots.py
- src/plugins/Core/plugins/_fakenode.py
- src/plugins/Core/plugins/account.py
- src/plugins/Core/plugins/bots.py
- src/plugins/Core/plugins/cave.py
- src/plugins/Core/plugins/email.py
- src/plugins/Core/plugins/etm/rubbish.py
> OpenShamrock 适配修复

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/_utils.py
- src/plugins/Core/plugins/bots.py
Add prompt for pulling merged forwards
- Add prompt for pulling information from a merged forward message
in order to provide context and enhance user experience when using
certain forwarded message features. This feature improves user
understanding when handling forwarded messages.
> [add] 添加合并转发拉取提示

- .github/workflows/auto-merge.yml
~~妈妈再也不用担心忘记加`[update]`啦！~~
> [!TIP]
> 此 PR 合并后的 PR 一经 approve 将会立即合并
> 使用 GitHub Actions 为 PR 启用 Auto Merge

- .github/workflows/auto-merge.yml
- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/_lang.py
- src/plugins/Core/plugins/_utils.py
- src/plugins/Core/plugins/su.py
> 触发器式 su 指令

- src/plugins/Core/plugins/userinfo.py
Refactor user panel data retrieval logic for userinfo plugin
Refactor the logic for adding user data to the panel to prevent duplicate entries and ensure data integrity. This change enhances the accuracy and consistency of user information displayed in the panel. No related issues.
> 修复用户从未签到时 panel 报错的问题

- .github/workflows/label-issue.yml
- .github/workflows/label-issues.yml
> [add] 在 Issue 被 PR 提及后修改 Issue 的 Label

- pyproject.toml
- src/plugins/Core/plugins/extra.py
> 添加插件: nonebot-plugin-servicestate 

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/preview.py
> [add] 为 Preview 添加  NSFW 检测

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/preview.py
- 将 NSFW 检测 api 更换为百度云接口，降低误报率
> 新的 `http://localhost:5000` 服务器端文件已经发给xd
> [update] 修改 NSFW 检测 api

- LICENSE
身份声明改为了 "IT Craft Development Team" 以更准确地反映代码的所有权和版权归属。
> 修改 LICENSE 中的 Author

- src/plugins/Core/plugins/_utils.py
- src/plugins/Core/plugins/gpt_scale_down.py
> [add] 自动缩减会话 (#538)

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/_error.py
- src/plugins/Core/plugins/latex.py
> [add] LaTeX 渲染

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/_utils.py
- src/plugins/Core/plugins/cave.py
- src/plugins/Core/plugins/preview.py
- 为 cave 添加内容审查
- 将内容审查功能独立为单独的函数
- 添加违规自动上报
> [add] 为 cave 添加内容审查

- src/plugins/Core/plugins/bag_tidy.py
> [add] 自动背包整理

- src/plugins/Core/plugins/bag.py
- src/plugins/Core/plugins/etm/bag.py
> 将背包计数修改为组数

- .github/workflows/label-issues.yml
> [update] 以「未计划」关闭 Issue 时不添加标签

- src/plugins/Core/plugins/chatgptv2.py
> [update] 支持回复 GPT

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/etm/achievement.json
- src/plugins/Core/plugins/etm/achievement.py
> [!NOTE]
> 使用 `asyncio.create_task` 是因为懒得重构
> 使用邮件代替信使发送成就解锁通知

- src/plugins/Core/plugins/email.py
- src/plugins/Core/plugins/etm/item.py
> 修复计算堆叠时出错的问题

- src/plugins/Core/plugins/cave.py
- src/plugins/Core/plugins/su_cave.py
> 使用指令修改 Cave 冷却时间

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/_utils.py
- src/plugins/Core/plugins/preview.py
- 添加审核失败时返回构造好的一条不合规信息
- 修改 preview 的违规提示信息
> [update] 对审核失败做错误处理

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/reply_probability.py
- src/plugins/Core/plugins/smart_reply.py
> [add] 允许自定义调教条目对群聊或用户的触发概率

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/etm/duel/buff/__init__.py
- src/plugins/Core/plugins/etm/duel/entity/__init__.py
- src/plugins/Core/plugins/etm/duel/entity/user.py
- src/plugins/Core/plugins/etm/duel/item.py
- src/plugins/Core/plugins/etm/duel/item/__init__.py
- src/plugins/Core/plugins/etm/duel/item/hand.py
- src/plugins/Core/plugins/etm/duel/item/passive.py
- src/plugins/Core/plugins/etm/duel/item/weapons.py
- src/plugins/Core/plugins/etm/duel/scheduler.py
- src/plugins/Core/plugins/etm/health.py
- src/plugins/Core/plugins/etm/items/stick.py
> 完成 Duel2 基本框架

- src/plugins/Core/disabled_plugins/essencemsg.py
- src/plugins/Core/plugins/etm/items/experience.py
- src/plugins/Core/plugins/etm/items/vimcoin.py
> 修改部分物品的堆叠上限

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/chatgptv2.py
- src/plugins/Core/plugins/etm/buff.py
- src/plugins/Core/plugins/etm/buffs.json
- src/plugins/Core/plugins/etm/item_list.py
- src/plugins/Core/plugins/etm/items/gpt_monthly_pass.py
- src/plugins/Core/plugins/etm/items/mystery_box.py
- src/plugins/Core/plugins/shop.py
> [add] 添加 XDbot GPT Plus++ (30d)

- src/plugins/Core/plugins/account.py
- src/plugins/Core/plugins/cave.py
- src/plugins/Core/plugins/etm/item_list.py
> [update] 允许投稿合并转发信息

- src/plugins/Core/plugins/preview.py
> [update] 自动 Preview 不响应 b23.tv、bilibili.com 等域名

- src/plugins/Core/plugins/_utils.py
- src/plugins/Core/plugins/email.py
- src/plugins/Core/plugins/quickmath.py
> 修复自动删除 EMAIL 不保存的问题

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/duel.py
- src/plugins/Core/plugins/etm/duel/entity/__init__.py
- src/plugins/Core/plugins/etm/duel/entity/user.py
- src/plugins/Core/plugins/etm/duel/item/weapons.py
- src/plugins/Core/plugins/etm/duel/logger.py
- src/plugins/Core/plugins/etm/duel/scheduler.py
达成成就: 凌晨两点半的 PR
晚安，各位
> 以为之前一点多很晚了，没想到还有更晚的
> [add] 新版 Duel 指令测试

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/etm/duel/buff/CriticalStrikeChanceIncreased.py
- src/plugins/Core/plugins/etm/duel/buff/__init__.py
- src/plugins/Core/plugins/etm/duel/entity/__init__.py
- src/plugins/Core/plugins/etm/duel/entity/user.py
- src/plugins/Core/plugins/etm/duel/item/passive.py
- src/plugins/Core/plugins/etm/duel/item/relic.py
- src/plugins/Core/plugins/etm/duel/item/weapons.py
- src/plugins/Core/plugins/etm/duel/scheduler.py
- src/plugins/Core/plugins/etm/item_list.py
- src/plugins/Core/plugins/etm/items/duel/passive/magic_cat.py
> [add] 装备: 猫耳（头部）

- src/plugins/Core/plugins/cave.py
> 回声洞内容仅存在图片时不进行文本审核

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/lib/FindingTheTrail/image.py
- src/plugins/Core/lib/FindingTheTrail/main.py
- src/plugins/Core/lib/FindingTheTrail/noise.py
- src/plugins/Core/plugins/_utils.py
- src/plugins/Core/plugins/ftt.py
> [add] 在展示 FTT 结果发送模拟运行图

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/status.py
> 在 Status 添加平均 Load

- src/plugins/Core/plugins/cave.py
> 回复 `cave-a` 消息时也可以添加评论

- src/plugins/Core/plugins/help.py
> [add] 指令帮助别名

- src/plugins/Core/lang/zh_hans.json
- src/plugins/Core/plugins/_error.py
- src/plugins/Core/plugins/_utils.py
- src/plugins/Core/plugins/help.py
- src/plugins/Core/plugins/statistics.py
> [add] 指令调用量统计

- src/plugins/Core/plugins/_error.py
> [fix] wssb

- src/plugins/Core/plugins/bots.py
> 允许部分 bot 在群聊不存在时不抛出错误

- src/plugins/Core/plugins/etm/items/dice.py
> 二十面骰子百分比显示出错

- pyproject.toml
- requirements.txt
- src/plugins/Core/plugins/extra.py
- **[add] plguin: picstat**
- **[add] help**
> [add] Plugin: nonebot-plugin-picmcstat

- src/plugins/Core/plugins/_error.py
- src/plugins/Core/plugins/_utils.py
- src/plugins/Core/plugins/chatgptv2.py
- src/plugins/Core/plugins/setu.py
> 对部分指令添加 Public QQBot 过滤

- src/plugins/Core/plugins/jrrp.py
因为 Sugar 那边也干了，XDbot2 这边也跟进下
我们这边覆盖时间比 Sugar 长点
> [update] jrrp: 中高考更新
